ANSIBLE_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:zdCU+ln43NjfrBS+cqdqaMuQYKHtyxdkW/nTOFT603q3QbHASbd8ihvHu4pqR0Fn7v1pOKBMBljK2TSV3OMQAog+u1G2ZS6G/QUxOQBAAuONE1nH8IolCfdqQwtET83V34WclYnUf6Da0p+Pgxpt3NEXvRSifsJESTbFaG25OpPb9eSOyZvGAyQOWDxnE9jmMPstGElfu4O8Ko35lx08LFFTHvsB6mga4fK+dk1nSnP+BgAwE4R1Ko24kH1Sl46buP4Zmsb2cwY4TqNKBxfu3vObrOR5uo7D3yJBiTh7Ic1XUhramJwaJ6zB+BDYcz8Qr7G1tgnrA70cmsgEBif3gcQUtdbnNWy2V/C/0XuCF+jHA4p+tgc3Y5QhWE3BM4g+KqhV1wVyIhlBiFWJp0UhcbUbqGdmsHtMUcUGD/S1e3NVaBFpnO5ktrbxh6h0shcgJh3mzLkBiyo/QvxyHVQbpO62hdGROgfvJ+F3mf6pxjVa1V0uaiu41To6MSZTeL3X7yE09E8sx7ZIHPajYfa88mE9C8raAnCsbD9ANiyGxaE5TC67JdiRZdZ6xMib95Z9QWmlIsYjXXZ77kXzOQjyIN5S9luTcpb3jOe1N0rynbRqNytJuOuvuqBnCMcyW9ZRCV1tIg8NcNA4RvUNWLvRcnHw7ARA1Na+Wg==,iv:kMlf9irSs5eYE2yhTejIE4tu9QT0FzmdyatI6rVqYKI=,tag:3q7WBi1sjZtzirNIWzpo2Q==,type:str]
hello: ENC[AES256_GCM,data:IREnkDzczTiIFGrXNfVjfQGXiveahwKOcEQuhqfrSwIG/KJe75M3lkl0KpdR+g==,iv:+N904s5fCRxFKVt5bRSsR8FFM01wr2CBlLZW8ECpx7w=,tag:TPxo1QgqsMKMTipHDnJOJQ==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Kzk0VjhzelRHY1hIVGlv
            cHZHaVZPcjV0K3NKZzRnK25EeUtzdjRrRmlRCkpYWk5ya2dzVzRVdWRPZzBVU2VJ
            NFRFcEljblM5clprOVpYNmxzQzlWeVUKLS0tIFMzM2NtZlVCZWZ1L1dKNHB0T2Y5
            U3pYTlJ1Uy9GdnI3UG5oUzAyQWN5eVkKz9nfrhDsIqUX1EXv4pw+tiikRj+WkaG1
            0DNdG0Wruj1VDJJQT+Tk275/kIFCGPdmq+UcRMbKY3q1pYQS1LEl+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T06:43:55Z"
    mac: ENC[AES256_GCM,data:ggwz7g8EdZHApDv+J7EDC6tcN5nA0g1jzNUfQpclup5SLqHEunYKta4caU8/D899IzUdbnrk4vxpbYyO9IQAX5FUXhEDY/b1IKT9VGZqkL3GGCO4BoBGrGHAQtKE8l9VLRy5fZKdpa2w1y8lp2ukJ7NDPLY0c1MOyS+7rB0HZno=,iv:BUP9PBuWOP2yiOKX7pvHYWmMs6jjMu5t5kMREido4h0=,tag:mjtikG1kgfMK9JPjL0A9ng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
