hello: ENC[AES256_GCM,data:IREnkDzczTiIFGrXNfVjfQGXiveahwKOcEQuhqfrSwIG/KJe75M3lkl0KpdR+g==,iv:+N904s5fCRxFKVt5bRSsR8FFM01wr2CBlLZW8ECpx7w=,tag:TPxo1QgqsMKMTipHDnJOJQ==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Kzk0VjhzelRHY1hIVGlv
            cHZHaVZPcjV0K3NKZzRnK25EeUtzdjRrRmlRCkpYWk5ya2dzVzRVdWRPZzBVU2VJ
            NFRFcEljblM5clprOVpYNmxzQzlWeVUKLS0tIFMzM2NtZlVCZWZ1L1dKNHB0T2Y5
            U3pYTlJ1Uy9GdnI3UG5oUzAyQWN5eVkKz9nfrhDsIqUX1EXv4pw+tiikRj+WkaG1
            0DNdG0Wruj1VDJJQT+Tk275/kIFCGPdmq+UcRMbKY3q1pYQS1LEl+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T15:19:53Z"
    mac: ENC[AES256_GCM,data:6t6Rna5Y/Pr7rNAfQ/AbwcDmU6ZTuos30ThqM+j3Q4Jb9mvb2QGuqzPd93tikd4w1PXcweItP9K5hUAAkFPw005BGVgvldyVQKAHjxcCESxwHTA7g4gqR0DCCAf+ZZecjVu2A/IadQwmA6qloDk1AZXxvAiZLc3ecv0BGTC4h0I=,iv:X2C8IFUVrNyRSlkV3OHeo2Lg1YDOgrtW7AFGmNvLqzA=,tag:qZRDsXiLpj2nJU+AQPQx/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
